---
permalink: online-help/concept-how-annotation-rules-work-in-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: 'Une règle d"annotation est un critère que vous définissez pour annoter les objets de stockage \(volumes, clusters ou machines virtuelles de stockage \(SVM\)\). Vous pouvez utiliser des groupes de condition ou des conditions pour définir des règles d"annotation.' 
---
= Fonctionnement des règles d'annotation dans Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une règle d'annotation est un critère que vous définissez pour annoter les objets de stockage (volumes, clusters ou SVM). Vous pouvez utiliser des groupes de condition ou des conditions pour définir des règles d'annotation.

* Vous devez associer une règle d'annotation à une annotation.
* Vous devez associer un type d'objet à une règle d'annotation ; un seul type d'objet peut être associé à une règle d'annotation.
* Unified Manager ajoute ou supprime des annotations des objets de stockage après chaque cycle de surveillance ou lors de la création, de la modification, de la suppression ou de la réorganisation d'une règle.
* Une règle d'annotation peut avoir un ou plusieurs groupes de condition et chaque groupe de condition peut avoir une ou plusieurs conditions.
* Les objets de stockage peuvent avoir plusieurs annotations. Une règle d'annotation pour une annotation particulière peut également utiliser différentes annotations dans les conditions de règle pour ajouter une autre annotation à des objets déjà annotés.




== Conditions

Vous pouvez créer plusieurs groupes de condition et chaque groupe de condition peut avoir une ou plusieurs conditions. Vous pouvez appliquer tous les groupes de condition définis dans une règle d'annotation d'une annotation afin d'annoter les objets de stockage.

Les conditions d'un groupe de conditions sont exécutées à l'aide de LA commande LOGIQUE ET. Toutes les conditions d'un groupe de conditions doivent être remplies. Lorsque vous créez ou modifiez une règle d'annotation, une condition est créée qui s'applique, sélectionne et annote uniquement les objets de stockage qui répondent à toutes les conditions du groupe de conditions. Vous pouvez utiliser plusieurs conditions au sein d'un groupe de conditions lorsque vous souhaitez restreindre la portée des objets de stockage à annoter.

Vous pouvez créer des conditions avec des objets de stockage en utilisant les opérandes et l'opérateur suivants et en spécifiant la valeur requise.

|===
| Type d'objet de stockage | Opérandes applicables 


 a| 
Volumétrie
 a| 
* Nom de l'objet
* Nom du cluster propriétaire
* Nom de SVM propriétaire
* Annotations




 a| 
SVM
 a| 
* Nom de l'objet
* Nom du cluster propriétaire
* Annotations




 a| 
Cluster
 a| 
* Nom de l'objet
* Annotations


|===
Lorsque vous sélectionnez annotation comme opérande pour un objet de stockage, l'opérateur « is » est disponible. Pour tous les autres opérandes, vous pouvez sélectionner « is » ou « contient » comme opérateur. Lorsque vous sélectionnez l'opérateur « is », la condition est évaluée pour une correspondance exacte entre la valeur de l'opérande et la valeur fournie pour l'opérande sélectionné. Lorsque vous sélectionnez l'opérateur « contient », la condition est évaluée pour satisfaire à l'un des critères suivants :

* La valeur d'opérande correspond exactement à la valeur de l'opérande sélectionné.
* La valeur opérande contient la valeur fournie pour l'opérande sélectionné.




== Exemple de règle d'annotation avec des conditions

Envisagez une règle d'annotation avec un groupe de conditions pour un volume avec les deux conditions suivantes :

* Le nom contient « vol ».
* Nom du SVM est « `date_svm' »


Cette règle d'annotation annote tous les volumes qui incluent « vol » dans leurs noms et qui sont hébergés sur des SVM sous le nom « `date_svm' » avec l'annotation sélectionnée et le type d'annotation.



== Groupes de condition

Les groupes de condition sont exécutés à l'aide D'UN OU logique, puis appliqués aux objets de stockage. Les objets de stockage doivent répondre aux exigences de l'un des groupes de condition à annoter. Les objets de stockage qui répondent aux conditions de tous les groupes de condition sont annotés. Vous pouvez utiliser des groupes de conditions pour augmenter la portée des objets de stockage à annoter.



== Exemple de règle d'annotation avec groupes de condition

Considérons une règle d'annotation avec deux groupes de condition pour un volume ; chaque groupe contient les deux conditions suivantes :

* Groupe de condition 1
+
** Le nom contient « vol ».
** SVM name est « data_svm » cette condition group annote tous les volumes, y compris « vol », dans leurs noms et qui sont hébergés sur des SVM sous le nom « `date_svm ».


* Groupe condition 2
+
** Le nom contient « vol ».
** La valeur d'annotation de la priorité des données est « critique » ce groupe de condition annote tous les volumes qui incluent « vol » dans leurs noms et qui sont annotés avec la valeur d'annotation prioritaire des données comme « critique ».




Lorsqu'une règle d'annotation contenant ces deux groupes de condition est appliquée aux objets de stockage, les objets de stockage suivants sont annotés :

* Tous les volumes qui incluent « vol » dans leurs noms et qui sont hébergés sur SVM sous le nom « data_svm ».
* Tous les volumes qui incluent « vol » dans leurs noms et qui sont annotés avec la valeur d'annotation prioritaire des données comme « critique ».

