---
permalink: online-help/concept-what-reports-do.html 
sidebar: sidebar 
keywords:  
summary: 'Les rapports affichent des informations détaillées sur les objets de stockage, ce qui vous permet d"examiner et d"identifier les problèmes potentiels.' 
---
= Que font les rapports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les rapports affichent des informations détaillées sur les objets de stockage, ce qui vous permet d'examiner et d'identifier les problèmes potentiels.

Vous pouvez enregistrer, supprimer, partager, planifier et importer des rapports. Vous pouvez également rechercher des rapports spécifiques. Vous pouvez personnaliser des rapports en fonction d'utilisations spécifiques et enregistrer le rapport personnalisé à des fins d'utilisation ultérieure. Vous pouvez effectuer d'autres opérations telles que le filtrage, le tri, le regroupement et le formatage.

Par défaut, chaque groupe de rapports est affiché par type et description de rapport. Vous pouvez exécuter des rapports pour afficher un groupe de rapports spécifique.

Une fois que vous avez exécuté un rapport, vous pouvez le personnaliser et enregistrer le rapport personnalisé. Vous pouvez afficher les rapports personnalisés qui sont enregistrés dans la page Rapports, regroupés sous la catégorie de rapport spécifique.

Vous pouvez planifier l'envoi des rapports ou les partager dans l'un des formats pris en charge : PDF, XHTML, CSV, XLS ou texte.

Vous pouvez exporter des rapports dans différents formats et les enregistrer sur votre bureau. Vous pouvez exporter des données de colonne individuelles à partir des rapports générés.

Vous pouvez importer des fichiers de conception de rapport (`.rptdesign` Fichiers) et enregistrez les rapports importés dans la page Rapports. Vous pouvez supprimer des rapports personnalisés et importés.

Vous pouvez importer les rapports suivants :

* Rapports avec plusieurs en-têtes dont la plage de colonnes est définie sur un
* Rapports avec graphiques uniquement
* Rapports avec listes et grilles uniquement


Les rapports au format texte, CSV et Excel sont pris en charge dans les scénarios suivants :

* Elément de table uniquement dans `.rptdesign` fichier
* Une table avec un seul en-tête comme ligne


Vous ne pouvez pas importer des rapports dont l'étendue de colonne est supérieure à une. Si un rapport au format texte, CSV ou Excel comporte plusieurs lignes d'en-tête, seule la première ligne d'en-tête est prise en compte et les lignes restantes sont ignorées.
