---
permalink: online-help/concept-what-jobs-are.html 
sidebar: sidebar 
keywords:  
summary: 'Un travail est une série de tâches que vous pouvez contrôler à l"aide d"Unified Manager. L"affichage des travaux et de leurs tâches associées vous permet de déterminer si un travail a réussi.' 
---
= Quels sont les emplois
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un travail est une série de tâches que vous pouvez contrôler à l'aide d'Unified Manager. L'affichage des travaux et de leurs tâches associées vous permet de déterminer si un travail a réussi.

Les tâches sont lancées lorsque vous créez des relations SnapMirror et SnapVault lorsque vous effectuez une quelconque opération de relation (rompre, éditer, suspendre, supprimer, reprendre, resynchroniser, et resynchroniser), lorsque vous effectuez des tâches de restauration des données, lorsque vous vous connectez à un cluster, etc.

Lorsque vous lancez une tâche, vous pouvez utiliser la page protection/travaux et la page protection/Détails de la tâche pour surveiller la tâche et la progression des tâches associées.
