---
permalink: online-help/reference-edit-vserver-with-infinite-volume-thresholds-dialog-box-iv.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser la boîte de dialogue Modifier SVM avec Infinite Volume Threshold pour modifier les valeurs de seuil par défaut de chaque SVM avec Infinite Volume, en fonction des besoins de votre entreprise. Les valeurs de seuil par défaut indiquent le niveau d"activité à atteindre sur la SVM avant qu"un événement ne soit déclenché.' 
---
= Modifiez le SVM avec la boîte de dialogue seuils d'Infinite Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la boîte de dialogue Modifier le SVM avec Infinite Volume Threshold pour modifier les valeurs de seuil par défaut de chaque SVM avec Infinite Volume, en fonction des besoins de votre entreprise. Les valeurs de seuil par défaut indiquent le niveau d'activité à atteindre sur la SVM avant qu'un événement ne soit déclenché.



== Puissance

La zone capacité vous permet de définir les conditions de seuil de capacité pour la SVM sélectionnée avec Infinite Volume :

* *Espace presque plein*
+
Spécifie le pourcentage auquel la SVM avec Infinite Volume est considérée comme presque pleine. Elle affiche également l'espace correspondant (en Go, Mo ou To) dans Infinite Volume. Par exemple, si vous avez un Infinite Volume de 10 Go et que le seuil espace presque plein est de 80 %, les informations suivantes s'affichent : (8 Go de 10 Go).

+
Vous pouvez également utiliser le curseur pour définir la valeur du seuil.

* *Espace plein*
+
Spécifie le pourcentage auquel la SVM avec Infinite Volume est considérée comme pleine. Elle affiche également l'espace correspondant (en Go, Mo ou To) dans Infinite Volume. Par exemple, si vous avez un Infinite Volume de 10 Go et que le seuil espace plein est de 90 %, les informations suivantes s'affichent : (9 Go de 10 Go).

+
Vous pouvez également utiliser le curseur pour définir la valeur du seuil.

* *Limite d'utilisation de l'instantané*
+
Spécifie la limite, en pourcentage, de l'espace réservé pour les copies Snapshot dans Infinite Volume.





== Boutons de commande

Les boutons de commande permettent d'effectuer les tâches suivantes :

* *Rétablir les valeurs par défaut globales*
+
Permet de restaurer les paramètres de seuil aux valeurs actuelles définies au niveau global.

* *Enregistrer*
+
Enregistre tous les paramètres de seuil.

* *Enregistrer et fermer*
+
Enregistre tous les paramètres de seuil, puis ferme la boîte de dialogue Modifier le SVM avec Infinite Volume Threshold.

* *Annuler*
+
Ignore les modifications des paramètres de seuil et ferme la boîte de dialogue Modifier le SVM avec des seuils d'Infinite Volume.


