---
permalink: online-help/reference-add-cluster-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez ajouter un cluster existant afin de contrôler le cluster et d"obtenir des informations sur son état, sa capacité, sa configuration et ses performances.' 
---
= Boîte de dialogue Ajouter un cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter un cluster existant afin de contrôler le cluster et d'obtenir des informations sur son état, sa capacité, sa configuration et ses performances.

Vous pouvez ajouter un cluster en spécifiant les valeurs suivantes :

* *Nom d'hôte ou adresse IP*
+
Permet de spécifier le nom d'hôte (privilégié) ou l'adresse IP (IPv4 ou IPv6) de la LIF de gestion du cluster utilisée pour se connecter au cluster. En spécifiant le nom d'hôte, vous pourrez faire correspondre le nom du cluster dans l'interface utilisateur Web, plutôt que de tenter de mettre en corrélation une adresse IP sur une page avec un nom d'hôte sur une autre page.

* *Nom d'utilisateur*
+
Permet de spécifier un nom d'utilisateur pouvant être utilisé pour vous connecter au cluster.

* *Mot de passe*
+
Vous permet de spécifier un mot de passe pour le nom d'utilisateur spécifié.

* *Protocole*
+
Permet de spécifier le type de protocole pouvant être configuré sur le cluster. Vous pouvez activer HTTP ou HTTPS (pour une connexion sécurisée). La connexion est établie avec le cluster via les deux protocoles et HTTPS est choisi via HTTP. Par défaut, HTTPS est activé avec le port par défaut 443.

* *Port*
+
Permet de spécifier le numéro de port utilisé pour se connecter au cluster. Si le port n'est pas spécifié, le port par défaut du protocole sélectionné est utilisé (80 pour HTTP ou 443 pour HTTPS).


