---
permalink: online-help/reference-aggregate-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: 'La page seuils de configuration/santé des agrégats vous permet de configurer les valeurs des seuils de santé globaux des agrégats surveillés. Lorsque vous configurez globalement les options, les valeurs par défaut de tous les objets sont modifiées. Cependant, si les valeurs par défaut ont été modifiées au niveau de l"objet, les valeurs globales ne sont pas modifiées.' 
---
= Page seuils de configuration/de santé des agrégats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page seuils de configuration/santé des agrégats vous permet de configurer les valeurs des seuils de santé globaux des agrégats surveillés. Lorsque vous configurez globalement les options, les valeurs par défaut de tous les objets sont modifiées. Cependant, si les valeurs par défaut ont été modifiées au niveau de l'objet, les valeurs globales ne sont pas modifiées.

Vous devez avoir le rôle d'administrateur OnCommand ou d'administrateur du stockage.

Les événements sont générés lorsqu'un seuil est atteint. Vous pouvez prendre des actions correctives pour de tels événements.

Les valeurs de seuil ne s'appliquent pas à l'agrégat racine du nœud.

Vous pouvez définir des seuils d'intégrité des agrégats pour : capacité, croissance de l'agrégat et copies Snapshot de l'agrégat.



== Surface de capacité

L'espace capacité vous permet de définir les conditions de seuil de capacité globale suivantes. Notez que lorsque la croissance automatique est activée sur les volumes qui résident sur l'agrégat, les seuils de capacité de l'agrégat sont considérés comme enfreintes pour la taille maximale du volume définie par la croissance automatique, et non pas pour la taille du volume initial.

* *Espace presque plein*
+
Spécifie le pourcentage auquel un agrégat est considéré comme presque plein :

+
** Valeur par défaut : 80 %
+
La valeur de ce seuil doit être inférieure à la valeur du seuil total global pour que le serveur de gestion puisse générer un événement.

** Événement généré : agrégat presque plein
** Gravité de l'événement : avertissement


* *Espace plein*
+
Spécifie le pourcentage auquel un agrégat est considéré comme complet :

+
** Valeur par défaut : 90 %
** Événement généré : total plein
** Gravité de l'événement : erreur


* *Presque surengagement*
+
Spécifie le pourcentage auquel un agrégat est considéré comme presque surengagé :

+
** Valeur par défaut : 95 %
+
La valeur de ce seuil doit être inférieure à la valeur du seuil total dépassé pour que le serveur de gestion génère un événement.

** Événement généré : agrégat presque dépassé
** Gravité de l'événement : avertissement


* *Surengagement*
+
Spécifie le pourcentage auquel un agrégat est considéré comme surallouate :

+
** Valeur par défaut : 100 %
** Événement généré : agrégat annulé
** Gravité de l'événement : erreur


* * Jours jusqu'à la pleine*
+
Spécifie le nombre de jours restants avant que l'agrégat n'atteigne sa pleine capacité :

+
** Valeur par défaut : 7
** Événement généré : total des jours jusqu'à la fin
** Gravité de l'événement : erreur






== Zone de croissance

La zone de croissance vous permet de définir les conditions seuils suivantes pour la croissance globale :

* *Taux de croissance*
+
Spécifie le pourcentage auquel le taux de croissance d'un agrégat est considéré comme normal avant que le système ne génère un événement anormal de taux de croissance global :

+
** Valeur par défaut : 1 %
** Événement généré : taux de croissance global anormal
** Gravité de l'événement : avertissement


* *Sensibilité du taux de croissance*
+
Spécifie le facteur qui est appliqué à l'écart-type du taux de croissance d'un agrégat. Si le taux de croissance dépasse l'écart-type pris en compte, un événement anormal de taux de croissance global est généré.

+
Une valeur plus faible pour la sensibilité au taux de croissance indique que l'agrégat est très sensible aux variations du taux de croissance. La plage de sensibilité de la vitesse de croissance est de 1 à 5.

+
** Valeur par défaut : 2


+
[NOTE]
====
Si vous modifiez la sensibilité au taux de croissance des agrégats au niveau du seuil global, la modification est également appliquée à la sensibilité au taux de croissance des volumes au niveau du seuil global.

====




== Zone des copies Snapshot

La zone copies Snapshot vous permet de définir les conditions de seuil de réserve Snapshot suivantes :

* *Réserve snapshot complète*
+
Spécifie le pourcentage auquel un agrégat a consommé tout l'espace réservé pour les copies Snapshot :

+
** Valeur par défaut : 90 %
** Événement généré : réserve Snapshot de l'agrégat saturée
** Gravité de l'événement : avertissement






== Boutons de commande

* *Rétablir les paramètres par défaut*
+
Permet de restaurer les paramètres de configuration aux valeurs par défaut.

* *Enregistrer*
+
Enregistre les paramètres de configuration pour l'option sélectionnée.


