---
permalink: online-help/reference-initialize-update-relationship-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 'La boîte de dialogue initialiser/mettre à jour vous permet d"effectuer un transfert de base de première fois sur une nouvelle relation de protection, ou de mettre à jour une relation si elle est déjà initialisée et que vous souhaitez effectuer une mise à jour manuelle, non programmée et incrémentielle.' 
---
= Boîte de dialogue initialiser/mettre à jour
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La boîte de dialogue initialiser/mettre à jour vous permet d'effectuer un transfert de base de première fois sur une nouvelle relation de protection, ou de mettre à jour une relation si elle est déjà initialisée et que vous souhaitez effectuer une mise à jour manuelle, non programmée et incrémentielle.



== Options de transfert

L'onglet Options de transfert vous permet de modifier la priorité d'initialisation d'un transfert et de modifier la bande passante utilisée pendant les transferts.

* *Priorité de transfert*
+
Priorité à laquelle le transfert est exécuté. Vous pouvez sélectionner Normal ou Bas. Relations avec des stratégies qui spécifient une priorité de transfert normale avant celles qui spécifient une priorité de transfert faible. Normal est sélectionné par défaut.

* *Taux de transfert max*
+
Spécifie la vitesse maximale à laquelle les données sont transférées entre les clusters sur le réseau. Si vous choisissez de ne pas utiliser un taux de transfert maximal, le transfert de base entre les relations est illimité. Toutefois, si vous exécutez ONTAP 8.2 et que le cluster principal et le cluster secondaire sont identiques, ce paramètre est ignoré. Si vous sélectionnez plusieurs relations avec des taux de transfert maximum différents, vous pouvez spécifier l'un des paramètres de taux de transfert maximum suivants :

+
** Utiliser les valeurs spécifiées lors de la configuration ou de la modification de relations individuelles
+
Lorsque cette option est sélectionnée, les opérations d'initialisation et de mise à jour utilisent la vitesse de transfert maximale spécifiée lors de la création ou de la modification de chaque relation. Ce champ est disponible uniquement lorsque plusieurs relations avec des taux de transfert différents sont initialisées ou mises à jour.

** Illimitée
+
Indique qu'il n'y a pas de limitation de bande passante sur les transferts entre relations. Ce champ est disponible uniquement lorsque plusieurs relations avec des taux de transfert différents sont initialisées ou mises à jour.

** Limitez la bande passante à
+
Lorsque cette option est sélectionnée, la bande passante réseau est limitée à la valeur que vous spécifiez. Vous pouvez entrer une valeur numérique, puis sélectionner kilo-octets par seconde (Kbit/s), mégaoctets par seconde (Mbit/s), gigaoctets par seconde (Gbit/s) ou téraoctets par seconde (Tbit/s). La vitesse de transfert maximale que vous spécifiez doit être supérieure à 1 kbps et inférieure à 4 Tbit/s.







== Onglet copies Snapshot source

L'onglet copies Snapshot source affiche les informations suivantes sur la copie Snapshot source utilisée pour le transfert de base :

* *Volume source*
+
Affiche les noms des volumes source correspondants.

* *Volume de destination*
+
Affiche les noms des volumes de destination sélectionnés.

* *Type de source*
+
Affiche le type de volume. Ce type peut être soit lecture/écriture, soit protection des données.

* *Copie snapshot*
+
Affiche la copie Snapshot utilisée pour le transfert de données. Si vous cliquez sur la valeur de la copie Snapshot, la boîte de dialogue Select source Snapshot Copy s'affiche. Vous pouvez alors sélectionner une copie Snapshot spécifique pour votre transfert, en fonction du type de relation de protection dont vous disposez et de l'opération que vous effectuez. La possibilité de spécifier une autre copie Snapshot n'est pas disponible pour les sources de type de protection des données.





== Boutons de commande

Les boutons de commande permettent d'effectuer les tâches suivantes :

* *Annuler*
+
Supprime vos sélections et ferme la boîte de dialogue initialiser/mettre à jour.

* *Soumettre*
+
Enregistre vos sélections et lance la tâche d'initialisation ou de mise à jour.


