---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez créer une relation SnapVault à l"aide de la page d"informations sur l"intégrité/le volume afin que les sauvegardes de données soient activées à des fins de protection sur des volumes.' 
---
= Création d'une relation de protection SnapVault à partir de la page des détails intégrité/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer une relation SnapVault à l'aide de la page d'informations sur l'intégrité/le volume afin que les sauvegardes de données soient activées à des fins de protection sur des volumes.



== Avant de commencer

* Vous devez avoir le rôle d'administrateur OnCommand ou d'administrateur du stockage.
* Vous devez avoir configuré Workflow Automation pour effectuer cette tâche.




== Description de la tâche

Le menu *Protect* ne s'affiche pas dans les cas suivants :

* Si les paramètres RBAC n'autorisent pas cette action : par exemple, si vous disposez uniquement des privilèges d'opérateur
* Lorsque l'ID du volume est inconnu : par exemple, lorsque vous avez une relation intercluster et que le cluster destination n'a pas encore été découvert




== Étapes

. Dans l'onglet *protection* de la page de détails *Santé/Volume*, cliquez avec le bouton droit de la souris sur un volume dans la vue topologique que vous souhaitez protéger.
. Sélectionnez *protéger* > *SnapVault* dans le menu.
+
La boîte de dialogue configurer la protection s'ouvre.

. Cliquez sur *SnapVault* pour afficher l'onglet *SnapVault* et configurer les informations de ressource secondaire.
. Cliquez sur *Advanced* pour définir la déduplication, la compression, la croissance automatique et la garantie d'espace selon les besoins, puis cliquez sur *Apply*.
. Renseignez la zone *destination information* et la zone *Relationship Settings* de la boîte de dialogue *Configure protection*.
. Cliquez sur *appliquer*.
+
Vous revenez à la page Détails de l'état/volume.

. Cliquez sur le lien de la tâche de configuration de la protection en haut de la page *Santé/Volume*.
+
La page protection/informations sur le travail s'affiche.

. Cliquez sur *Actualiser* pour mettre à jour la liste des tâches et les détails des tâches associés à la tâche de configuration de protection et déterminer quand la tâche est terminée.
+
Une fois les tâches terminées, les nouvelles relations s'affichent dans la vue topologique de la page Détails de l'état/volume.


