---
permalink: online-help/task-removing-a-protection-relationship.html 
sidebar: sidebar 
keywords:  
summary: 'Dans la page relations protection/volume, vous pouvez supprimer une relation de protection pour supprimer définitivement une relation existante entre la source et la destination sélectionnée : par exemple, lorsque vous souhaitez créer une relation à l"aide d"une autre destination. Cette opération supprime toutes les métadonnées et ne peut pas être annulée.' 
---
= Suppression d'une relation de protection de la page relations protection/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans la page relations protection/volume, vous pouvez supprimer une relation de protection pour supprimer définitivement une relation existante entre la source et la destination sélectionnée : par exemple, lorsque vous souhaitez créer une relation à l'aide d'une autre destination. Cette opération supprime toutes les métadonnées et ne peut pas être annulée.



== Avant de commencer

* Vous devez avoir le rôle d'administrateur OnCommand ou d'administrateur du stockage.
* Vous devez avoir configuré Workflow Automation.




== Étapes

. Dans la page *protection/relations de volume*, sélectionnez un ou plusieurs volumes avec des relations de protection que vous souhaitez supprimer et, dans la barre d'outils, cliquez sur *Supprimer*.
+
La boîte de dialogue Supprimer la relation s'affiche.

. Cliquez sur *Continuer* pour supprimer la relation.
+
La relation est supprimée de la page relations protection/volume.


