---
permalink: online-help/task-resynchronizing-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez resynchroniser les données d"une relation SnapMirror ou SnapVault interrompue, puis la destination a été créée en lecture/écriture afin que les données de la source correspondent aux données de destination. Vous pouvez également resynchroniser lorsqu"une copie Snapshot commune requise sur le volume source est supprimée, entraînant l"échec des mises à jour de SnapMirror ou de SnapVault.' 
---
= Resynchronisation des relations de protection à partir de la page Détails de l'intégrité/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez resynchroniser les données d'une relation SnapMirror ou SnapVault interrompue, puis la destination a été créée en lecture/écriture afin que les données de la source correspondent aux données de destination. Vous pouvez également resynchroniser lorsqu'une copie Snapshot commune requise sur le volume source est supprimée, entraînant l'échec des mises à jour de SnapMirror ou de SnapVault.



== Avant de commencer

* Vous devez avoir le rôle d'administrateur OnCommand ou d'administrateur du stockage.
* Vous devez avoir configuré OnCommand Workflow Automation.




== Étapes

. Dans l'onglet *protection* de la page de détails *Santé/Volume*, localisez dans la topologie la relation de protection que vous souhaitez resynchroniser et cliquez dessus avec le bouton droit de la souris.
. Sélectionnez *Resynchroniser* dans le menu.
+
Vous pouvez également sélectionner *relations* > *Resynchroniser* dans le menu *actions* pour resynchroniser la relation pour laquelle vous consultez actuellement les détails.

+
La boîte de dialogue Resynchroniser s'affiche.

. Dans l'onglet *Resynchronisation Options*, sélectionnez une priorité de transfert et le taux de transfert maximal.
. Cliquez sur *copies snapshot source*, puis, dans la colonne *copie snapshot*, cliquez sur *par défaut*.
+
La boîte de dialogue Sélectionner une copie Snapshot source s'affiche.

. Pour spécifier une copie Snapshot existante plutôt que de transférer la copie Snapshot par défaut, cliquez sur *copie Snapshot existante* et sélectionnez une copie Snapshot dans la liste.
. Cliquez sur *soumettre*.
+
Vous revenez à la boîte de dialogue Resynchroniser.

. Si vous avez sélectionné plusieurs sources à resynchroniser, cliquez sur *default* pour la source suivante pour laquelle vous souhaitez spécifier une copie Snapshot existante.
. Cliquez sur *Submit* pour lancer le travail de resynchronisation.
+
Le travail de resynchronisation est lancé, vous êtes renvoyé à la page Détails de l'état/volume et un lien tâches s'affiche en haut de la page.

. Cliquez sur *Afficher les travaux* sur la page de détails *Santé/Volume* pour suivre l'état de chaque travail de resynchronisation.
+
Une liste filtrée des travaux s'affiche.

. Cliquez sur la flèche Précédent de votre navigateur pour revenir à la page de détails *Santé/Volume*.
+
La tâche de resynchronisation est terminée lorsque toutes les tâches de travail sont terminées avec succès.


