---
permalink: online-help/task-viewing-the-svm-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: 'Dans la page d"inventaire Health/Storage Virtual machines, vous pouvez surveiller l"inventaire de vos machines virtuelles de stockage \(SVM\). Vous pouvez utiliser la page détaillée d"Health/Storage Virtual machine pour afficher des informations détaillées sur les SVM surveillés.' 
---
= Affichage de la liste des SVM et des détails
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de la page d'inventaire Health/Storage Virtual machines, vous pouvez surveiller votre inventaire des machines virtuelles de stockage (SVM). Vous pouvez utiliser la page détaillée d'Health/Storage Virtual machine pour afficher des informations détaillées sur les SVM surveillés.



== Avant de commencer

Vous devez avoir le rôle opérateur, administrateur OnCommand ou administrateur stockage.



== Description de la tâche

Vous pouvez afficher des détails relatifs aux SVM, comme la capacité, l'efficacité et la configuration d'un SVM. Vous pouvez également afficher des informations sur les périphériques associés et les alertes associées pour ce SVM.



== Étapes

. Dans le volet de navigation de gauche, cliquez sur *Santé* > *SVM*.
. Choisir l'une des méthodes suivantes pour afficher les détails du SVM :
+
** Pour afficher les détails minimes, positionner le curseur sur le nom de la SVM.
** Pour afficher les détails complets, cliquez sur le nom du SVM.
+
Vous pouvez également afficher les détails complets en cliquant sur *Afficher les détails* dans la boîte de dialogue Détails minimaux.



. Afficher les objets liés à la SVM en cliquant sur *View Related* dans la boîte de dialogue des détails minimaux.

