---
permalink: online-help/task-initializing-or-updating-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez effectuer un transfert de base initial sur une nouvelle relation de protection, ou mettre à jour une relation si elle est déjà initialisée et si vous souhaitez effectuer une mise à jour incrémentielle manuelle et non planifiée pour transférer immédiatement les données. 
---
= Initialisation ou mise à jour des relations de protection à partir de la page Détails de l'état/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer un transfert de base initial sur une nouvelle relation de protection, ou mettre à jour une relation si elle est déjà initialisée et si vous souhaitez effectuer une mise à jour incrémentielle manuelle et non planifiée pour transférer immédiatement les données.



== Avant de commencer

* Vous devez avoir le rôle d'administrateur OnCommand ou d'administrateur du stockage.
* Vous devez avoir configuré OnCommand Workflow Automation.




== Étapes

. Dans l'onglet *protection* de la page de détails *Santé/Volume*, localisez dans la topologie la relation de protection que vous souhaitez initialiser ou mettre à jour, puis cliquez dessus avec le bouton droit de la souris.
. Sélectionnez *initialiser/mettre à jour* dans le menu.
+
Vous pouvez également sélectionner *relations* > *initialiser/mettre à jour* dans le menu *actions* pour initialiser ou mettre à jour la relation pour laquelle vous consultez actuellement les détails.

+
La boîte de dialogue initialiser/mettre à jour s'affiche.

. Dans l'onglet *Options de transfert*, sélectionnez une priorité de transfert et le taux de transfert maximal.
. Cliquez sur *copies snapshot source*, puis, dans la colonne *copie snapshot*, cliquez sur *par défaut*.
+
La boîte de dialogue Sélectionner une copie Snapshot source s'affiche.

. Pour spécifier une copie Snapshot existante plutôt que de transférer la copie Snapshot par défaut, cliquez sur *copie Snapshot existante* et sélectionnez une copie Snapshot dans la liste.
. Cliquez sur *soumettre*.
+
Vous revenez à la boîte de dialogue initialiser/mettre à jour.

. Si vous avez sélectionné plusieurs sources à initialiser ou à mettre à jour, cliquez sur *default* pour la source de lecture/écriture suivante pour laquelle vous souhaitez spécifier une copie Snapshot existante.
+
Vous ne pouvez pas sélectionner une autre copie Snapshot pour les volumes de protection des données.

. Cliquez sur *Submit* pour lancer la tâche d'initialisation ou de mise à jour.
+
La tâche d'initialisation ou de mise à jour est démarrée, vous êtes renvoyé à la page Détails du volume/de l'état et un lien tâches s'affiche en haut de la page.

. Cliquez sur *Afficher les tâches* sur la page de détails *Santé/Volume* pour suivre l'état de chaque tâche d'initialisation ou de mise à jour.
+
Une liste filtrée des travaux s'affiche.

. Cliquez sur chaque travail pour en afficher les détails.
. Cliquez sur la flèche Précédent de votre navigateur pour revenir à la page de détails *Santé/Volume*.
+
L'opération d'initialisation ou de mise à jour est terminée lorsque toutes les tâches sont terminées avec succès.


