---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser la page d"inventaire Santé/volumes pour créer des relations SnapVault pour un ou plusieurs volumes sur la même machine virtuelle de stockage \(SVM\) afin de permettre les sauvegardes de données à des fins de protection.' 
---
= Création d'une relation de protection SnapVault à partir de la page d'inventaire Santé/volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la page d'inventaire Santé/volumes pour créer des relations SnapVault pour un ou plusieurs volumes sur la même machine virtuelle de stockage (SVM) afin de permettre la sauvegarde des données à des fins de protection.



== Avant de commencer

Vous devez avoir le rôle d'administrateur OnCommand ou d'administrateur du stockage.



== Description de la tâche

Le menu *Protect* ne s'affiche pas dans les cas suivants :

* Si les paramètres RBAC n'autorisent pas cette action : par exemple, si vous disposez uniquement des privilèges d'opérateur
* Lorsque l'ID du volume est inconnu : par exemple, lorsque vous avez une relation intercluster et que le cluster destination n'a pas encore été découvert




== Étapes

. Dans le volet de navigation de gauche, cliquez sur *Santé* > *volumes*.
. Dans la page d'inventaire *Santé/volumes*, cliquez avec le bouton droit de la souris sur un volume que vous voulez protéger et sélectionnez *protéger*.
+
Sinon, pour créer plusieurs relations de protection sur la même machine virtuelle de stockage (SVM), sélectionnez un ou plusieurs volumes dans la page d'inventaire Santé/volumes, puis cliquez sur *protéger* dans la barre d'outils.

. Sélectionnez *SnapVault* dans le menu.
+
La boîte de dialogue configurer la protection s'ouvre.

. Cliquez sur *SnapVault* pour afficher l'onglet *SnapVault* et configurer les informations relatives au volume secondaire.
. Cliquez sur *Advanced* pour définir la déduplication, la compression, la croissance automatique et la garantie d'espace selon les besoins, puis cliquez sur *Apply*.
. Renseignez la zone *destination information* et la zone *Relationship Settings* de l'onglet *SnapVault*.
. Cliquez sur *appliquer*.
+
Vous êtes renvoyé à la page d'inventaire Health/Volume.

. Cliquez sur le lien du travail de configuration de la protection en haut de la page d'inventaire *Santé/volumes*.
+
Si vous créez une seule relation de protection, la page Détails de protection/travail s'affiche. Cependant, si vous créez plusieurs relations de protection, une liste filtrée de tous les travaux associés à l'opération de protection s'affiche.

. Effectuez l'une des opérations suivantes :
+
** Si vous n'avez qu'un seul travail, cliquez sur *Actualiser* pour mettre à jour la liste des tâches et les détails des tâches associés à la tâche de configuration de protection et déterminer quand la tâche est terminée.
** Si vous avez plusieurs travaux :
+
... Cliquez sur un travail dans la liste des travaux.
... Cliquez sur *Actualiser* pour mettre à jour la liste des tâches et les détails des tâches associés à la tâche de configuration de protection et déterminer quand la tâche est terminée.
... Utilisez le bouton *Retour* pour revenir à la liste filtrée et afficher un autre travail.





