---
permalink: online-help/task-moving-workloads-to-a-node-in-a-different-ha-pair.html 
sidebar: sidebar 
keywords:  
summary: 'Unified Manager vous permet d"identifier un agrégat sur un nœud dans une autre paire haute disponibilité \(HA\) dont la capacité de performances est plus élevée que la paire haute disponibilité où vos workloads sont en cours d"exécution. Vous pouvez ensuite déplacer les volumes sélectionnés vers des agrégats sur la nouvelle paire haute disponibilité.' 
---
= Déplacement des workloads vers un nœud dans une autre paire haute disponibilité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager permet d'identifier un agrégat sur un nœud d'une autre paire haute disponibilité avec plus de capacité de performances que la paire haute disponibilité sur laquelle sont actuellement exécutées vos charges de travail. Vous pouvez ensuite déplacer les volumes sélectionnés vers des agrégats sur la nouvelle paire haute disponibilité.



== Avant de commencer

* Vous devez avoir le rôle opérateur, administrateur OnCommand ou administrateur stockage.
* Votre cluster doit comprendre au moins deux paires haute disponibilité
+
Ce processus de résolution des problèmes ne peut pas être utilisé si le cluster ne compte qu'une seule paire haute disponibilité.

* Vous devez avoir enregistré les noms des deux nœuds de la paire haute disponibilité qui présentent actuellement un problème de performances.
* Vous devez avoir enregistré la date et l'heure à laquelle les nœuds ont reçu l'événement de performance.
* Vous devez avoir enregistré l'ID d'événement, par exemple « p-sdt-cluse1-nod-6982 ».
* Unified Manager doit avoir collecté et analysé les données de performances pendant un mois ou plus.




== Description de la tâche

Le déplacement de charges de travail hautes performances vers un agrégat d'un nœud présentant une capacité plus élevée en termes de performances permet aux charges de travail des deux nœuds d'être plus efficaces. Cette procédure vous aide à identifier les ressources suivantes pour déplacer les charges de travail haute performance vers un nœud qui dispose de plus de capacité de performances disponible sur une autre paire haute disponibilité :

* Les nœuds d'une paire haute disponibilité différente sur le même cluster qui présentent la plus grande capacité de performances libres
* Les agrégats des nouveaux nœuds qui offrent la meilleure capacité de performances disponible
* Les volumes les plus performants sur les nœuds actuels




== Étapes

. Identifiez les nœuds qui font partie d'une autre paire haute disponibilité sur le même cluster :
+
.. Sur la page *Détails de l'événement*, cliquez sur le nom du cluster sur lequel se trouvent les nœuds.
+
Les détails du cluster s'affichent sur la page d'accueil Performance/Cluster.

.. Sur la page *Résumé*, cliquez sur *noeuds* dans le volet *objets gérés*.
+
La liste des nœuds de ce cluster est affichée sur la page Performance/nœuds.

.. Écrire les noms des nœuds qui se trouvent dans différentes paires haute disponibilité de la paire haute disponibilité actuellement ayant un problème de performances.


. Identifiez un nœud dans la nouvelle paire haute disponibilité qui présente la capacité de performances la plus élevée :
+
.. Sur la page *Performance/Nodes*, cliquez sur la colonne *Performance Capacity Used* pour trier les nœuds par le pourcentage le moins utilisé.
+
Vous trouverez ainsi une liste de nœuds potentiels vers lesquels vous pouvez déplacer des charges de travail.

.. Écrire le nom du nœud sur une autre paire HA vers laquelle vous souhaitez déplacer les charges de travail


. Identifiez un agrégat sur le nouveau nœud qui présente la capacité de performances la plus élevée :
+
.. Sur la page *Performance/Nodes*, cliquez sur le nœud.
+
Les détails des nœuds s'affichent sur la page Performance/Node Explorer.

.. Dans le menu *View and compare*, sélectionnez *Aggregates sur ce noeud*.
+
Les agrégats de ce nœud s'affichent dans la grille.

.. Cliquez sur la colonne *capacité de performance utilisée* pour trier les agrégats par le moins utilisé.
+
Ainsi, vous disposez d'une liste d'agrégats potentiels vers lesquels vous pouvez déplacer des charges de travail.

.. Écrire le nom de l'agrégat dans lequel vous souhaitez déplacer les charges de travail.


. Identifiez les charges de travail haute performance issues des nœuds qui ont reçu l'événement :
+
.. Revenez à la page *Event* details de l'événement.
.. Dans le champ *volumes affectés*, cliquez sur le lien correspondant au nombre de volumes du premier nœud.
+
La page Performance/volumes s'affiche avec une liste filtrée des volumes de ce nœud.

.. Cliquez sur la colonne *capacité totale* pour trier les volumes selon le plus grand espace alloué.
+
Cela fournit une liste de volumes potentiels que vous pouvez déplacer.

.. Notez les noms des volumes que vous souhaitez déplacer, ainsi que le nom des agrégats actuels où ils résident.
.. Exécutez les étapes 4c et 4d pour le second nœud qui faisait partie de cet événement pour identifier les volumes que vous souhaitez également déplacer à partir de ce nœud.


. Déplacez les volumes vers les agrégats que vous avez identifiés comme présentant la meilleure capacité de performances disponible sur le nouveau nœud.
+
Vous pouvez effectuer l'opération de déplacement en utilisant OnCommand System Manager, OnCommand Workflow Automation et les commandes ONTAP ou une combinaison de ces outils.





== Une fois que vous avez terminé

Après quelques jours, vous pouvez vérifier si vous recevez le même type d'événements du même nœud ou de l'agrégat.
