---
permalink: online-help/task-viewing-the-list-of-snapshot-copies.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez afficher la liste des copies Snapshot d"un volume sélectionné. Vous pouvez utiliser la liste des copies Snapshot pour calculer la quantité d"espace disque pouvant être récupérée si une ou plusieurs copies Snapshot sont supprimées, et vous pouvez supprimer les copies Snapshot si nécessaire.' 
---
= Affichage de la liste des copies Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la liste des copies Snapshot d'un volume sélectionné. Vous pouvez utiliser la liste des copies Snapshot pour calculer la quantité d'espace disque pouvant être récupérée si une ou plusieurs copies Snapshot sont supprimées, et vous pouvez supprimer les copies Snapshot si nécessaire.



== Avant de commencer

* Vous devez avoir le rôle opérateur, administrateur OnCommand ou administrateur stockage.
* Le volume contenant les copies Snapshot doit être en ligne.




== Étapes

. Dans le volet de navigation de gauche, cliquez sur *Santé* > *volumes*.
. Dans la page d'inventaire *Health/volumes*, sélectionnez le volume qui contient les copies Snapshot que vous souhaitez afficher.
. Dans la page de détails *Santé/Volume*, cliquez sur l'onglet *capacité*.
. Dans le volet *Détails* de l'onglet *capacité*, dans la section autres détails, cliquez sur le lien en regard de *copies snapshot*.
+
Le nombre de copies Snapshot est un lien qui affiche la liste des copies Snapshot.


