---
permalink: online-help/task-rediscovering-clusters.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez redécouvrir manuellement un cluster à partir de la page sources de données de configuration/cluster afin d"obtenir les dernières informations sur l"état de santé, la surveillance de l"état et les performances du cluster.' 
---
= Détection des clusters à nouveau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez redécouvrir manuellement un cluster à partir de la page sources de données de configuration/cluster afin d'obtenir les dernières informations sur l'état de santé, la surveillance de l'état et les performances du cluster.



== Description de la tâche

Vous pouvez redécouvrir manuellement un cluster lorsque vous souhaitez mettre à jour le cluster, par exemple en augmentant la taille d'un agrégat lorsque l'espace est insuffisant, et vous souhaitez qu'Unified Manager détecte les modifications que vous apportez.

Lorsque Unified Manager est associé à OnCommand Workflow Automation (WFA), le couplage déclenche la reacquisition des données mises en cache par WFA.



== Étapes

. Dans le volet de navigation de gauche, cliquez sur *Configuration* > *sources de données de cluster*.
. Sur la page *sources de données de configuration/cluster*, cliquez sur *redécouvrir*.
+
Unified Manager détecte de nouveau le cluster sélectionné et affiche le dernier état de santé et de performances.

+
[NOTE]
====
Vous pouvez obtenir l'état de contrôle du cluster depuis le volet droit de la page tableaux de bord/Cluster View.

====

