---
permalink: performance-checker/reference-performance-data-that-can-be-sent-to-an-external-server.html 
sidebar: sidebar 
keywords:  
summary: 'Unified Manager collecte de nombreuses données de performances dans tous les clusters qu"il surveille. Vous pouvez envoyer des groupes de données spécifiques à un serveur externe.' 
---
= Données de performances qui peuvent être envoyées à un serveur externe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager collecte de nombreuses données de performances dans tous les clusters qu'il surveille. Vous pouvez envoyer des groupes de données spécifiques à un serveur externe.

En fonction des données de performances que vous voulez saisir, vous pouvez choisir d'envoyer l'un des groupes de statistiques suivants :

|===
| Groupe de statistiques | Données incluses | Détails 


 a| 
Contrôle des performances
 a| 
Statistiques de performances générales pour les objets suivants :

* LUN
* Volumes

 a| 
Ce groupe fournit une latence totale ou des IOPS pour tous les LUN et volumes de tous les clusters surveillés.

Ce groupe fournit le plus petit nombre de statistiques.



 a| 
Utilisation des ressources
 a| 
Statistiques d'utilisation des ressources pour les objets suivants :

* Nœuds
* 64 bits

 a| 
Ce groupe fournit des statistiques d'utilisation du nœud et regroupe les ressources physiques dans tous les clusters surveillés.

Il fournit également les statistiques collectées dans le groupe moniteur de performances.



 a| 
Accédez à des informations détaillées
 a| 
Statistiques de lecture/écriture de niveau inférieur et statistiques par protocole pour tous les objets suivis :

* Nœuds
* 64 bits
* LUN
* Volumes
* Disques
* LIF
* Ports/NIC

 a| 
Ce groupe fournit des ventilations en lecture/écriture et par protocole pour les sept types d'objets suivis dans tous les clusters surveillés.

Il fournit également les statistiques collectées dans le groupe moniteur de performances et dans le groupe utilisation des ressources.

Ce groupe fournit le plus grand nombre de statistiques.

|===
[NOTE]
====
Si le nom d'un cluster, ou d'un objet cluster, est modifié sur le système de stockage, l'ancien et le nouveau objets contiennent des données de performances sur le serveur externe (appelé « chemin_métrique »). Les deux objets ne sont pas corrélés au même objet. Par exemple, si vous modifiez le nom d'un volume de « Volume 1_acct » à « acct_vol1 », vous verrez d'anciennes données de performances de l'ancien volume et de nouvelles données de performances du nouveau volume.

====
Consultez l'article de la base de connaissances pour obtenir la liste de tous les compteurs de performances pouvant être envoyés à un fournisseur de données externe.

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FActive_IQ_Unified_Manager%2FWhat_are_the_ActiveIQ_Unified_Manager_performance_counters_that_can_be_exported_to_an_External_Data_Provider%253F["Compteurs de performances Unified Manager pouvant être exportés vers un fournisseur de données externe"]
