---
permalink: performance-checker/task-responding-to-a-system-defined-node-resources-overutilized-performance-event.html 
sidebar: sidebar 
keywords:  
summary: 'Unified Manager génère des événements d"avertissement surexploités lorsqu"un nœud se trouve au-dessus des limites de son efficacité opérationnelle, et risque par conséquent d"affecter la latence des charges de travail. Ces événements définis par le système permettent de corriger les problèmes de performance potentiels avant que de nombreuses charges de travail ne soient affectées par la latence.' 
---
= Réponse aux événements de performance surexploités relatifs aux ressources des nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager génère des événements d'avertissement surexploités lorsqu'un nœud se trouve au-dessus des limites de son efficacité opérationnelle, et risque par conséquent d'affecter la latence des charges de travail. Ces événements définis par le système permettent de corriger les problèmes de performance potentiels avant que de nombreuses charges de travail ne soient affectées par la latence.



== Avant de commencer

* Vous devez avoir le rôle opérateur, administrateur OnCommand ou administrateur stockage.
* En effet, il doit y avoir de nouveaux événements ou des événements de performances obsolètes.




== Description de la tâche

Unified Manager génère des événements d'avertissement pour les violations de règles mises en excès de ressources de nœud en recherchant les nœuds qui utilisent plus de 100 % de leur capacité de performance pendant plus de 30 minutes.

Vous pouvez utiliser System Manager ou les commandes ONTAP pour corriger ce type de problème de performance, notamment les tâches suivantes :

* Création et application d'une politique de QoS à tous les volumes ou LUN sur-utilisant les ressources système
* Réduction de la limite de débit maximal de QoS d'un groupe de règles auquel des workloads ont été appliqués
* Déplacement d'une charge de travail vers un autre agrégat ou nœud
* Augmentation de la capacité par l'ajout de disques au nœud ou par mise à niveau vers un nœud avec un processeur plus rapide et plus de RAM




== Étapes

. Affichez la page *Event* details pour afficher des informations sur l'événement.
. Consultez la *Description*, qui décrit la violation de seuil qui a causé l'événement.
+
Par exemple, le message « Perf. La valeur utilisée de la capacité de 139 % sur la simplicité-02 a déclenché un événement D'AVERTISSEMENT pour identifier les problèmes de performances potentiels dans l'unité de traitement des données.» indique que la capacité de performances sur la simplicité du nœud 02 est surutilisée et affecte les performances du nœud.

. Dans la section *diagnostic du système*, examinez les trois graphiques : un pour la capacité de performance utilisée sur le nœud, un pour les IOPS de stockage moyennes utilisées par les principales charges de travail et un pour la latence sur les principales charges de travail. Lorsqu'elle est organisée, vous pouvez voir les workloads à l'origine de la latence sur le nœud.
+
Vous pouvez afficher les charges de travail appliquées aux règles de QoS et celles qui ne le sont pas en déplaçant le curseur sur le graphique des IOPS.

. Dans la section *actions suggérées*, examinez les suggestions et déterminez les actions que vous devez effectuer afin d'éviter une augmentation de la latence de la charge de travail.
+
Si nécessaire, cliquez sur le bouton *aide* pour afficher plus de détails sur les actions suggérées que vous pouvez effectuer pour tenter de résoudre l'événement de performance.


