---
permalink: performance-checker/task-sorting-on-the-object-inventory-performance-pages.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez trier toutes les données sur les pages performances de l"inventaire des objets par colonne dans l"ordre croissant ou décroissant. Cela vous permet de localiser rapidement les données d"inventaire des objets, ce qui est utile lors de l"examen des performances ou du début d"un processus de dépannage.' 
---
= Tri sur les pages performances de l'inventaire des objets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez trier toutes les données sur les pages performances de l'inventaire des objets par colonne dans l'ordre croissant ou décroissant. Cela vous permet de localiser rapidement les données d'inventaire des objets, ce qui est utile lors de l'examen des performances ou du début d'un processus de dépannage.



== Description de la tâche

La colonne sélectionnée pour le tri est indiquée par un nom d'en-tête de colonne en surbrillance et une icône de flèche indiquant la direction de tri à droite du nom. Une flèche vers le haut indique l'ordre croissant ; une flèche vers le bas indique l'ordre décroissant. L'ordre de tri par défaut est par *Status* (criticité de l'événement) dans l'ordre décroissant, avec les événements de performance les plus critiques répertoriés en premier.



== Étapes

. Vous pouvez cliquer sur un nom de colonne pour activer ou désactiver l'ordre de tri de la colonne dans l'ordre croissant ou décroissant.
+
Le contenu de la page performances de l'inventaire des objets est trié par ordre croissant ou décroissant, en fonction de la colonne sélectionnée.


