---
permalink: health-checker/concept-unified-manager-interfaces-used-to-manage-storage-system-health.html 
sidebar: sidebar 
keywords:  
summary: 'Cette section présente des informations sur les deux interfaces utilisateur fournies par OnCommand Unified Manager pour la résolution des problèmes de capacité, de disponibilité et de protection des données. Les deux interfaces utilisateur sont l"interface utilisateur Web de Unified Manager et la console de maintenance.' 
---
= Les interfaces Unified Manager utilisées pour gérer l'état du système de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette section présente des informations sur les deux interfaces utilisateur fournies par OnCommand Unified Manager pour la résolution des problèmes de capacité, de disponibilité et de protection des données. Les deux interfaces utilisateur sont l'interface utilisateur Web de Unified Manager et la console de maintenance.

Si vous souhaitez utiliser les fonctions de protection dans Unified Manager, vous devez également installer et configurer OnCommand Workflow Automation (WFA).



== Interface Web Unified Manager

L'interface utilisateur Web Unified Manager permet à un administrateur de surveiller et de résoudre les problèmes liés à la capacité de stockage, à la disponibilité et à la protection des données en cluster.

Cette section décrit les flux de travail courants à suivre pour résoudre les problèmes de capacité de stockage, de disponibilité des données ou de protection affichés dans l'interface utilisateur Web Unified Manager.



== Console de maintenance

La console de maintenance permet à un administrateur de surveiller, diagnostiquer et résoudre les problèmes liés au système d'exploitation, aux problèmes de mise à niveau de la version, aux problèmes d'accès utilisateur et aux problèmes réseau liés au serveur Unified Manager lui-même. Si l'interface utilisateur Web de Unified Manager n'est pas disponible, la console de maintenance est la seule forme d'accès à Unified Manager.

Cette section fournit des instructions pour accéder à la console de maintenance et l'utiliser pour résoudre les problèmes liés au fonctionnement du serveur Unified Manager.
