---
permalink: health-checker/task-changing-the-umadmin-password-on-rhel.html 
sidebar: sidebar 
keywords:  
summary: 'Pour des raisons de sécurité, vous devez modifier le mot de passe par défaut de l"utilisateur Unified Manager umadmin immédiatement après avoir terminé l"installation. Si nécessaire, vous pouvez modifier le mot de passe à nouveau ultérieurement.' 
---
= Modification du mot de passe umadmin sur les systèmes Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour des raisons de sécurité, vous devez modifier le mot de passe par défaut de l'utilisateur Unified Manager umadmin immédiatement après avoir terminé l'installation. Si nécessaire, vous pouvez modifier le mot de passe à nouveau ultérieurement.



== Avant de commencer

* Unified Manager doit être installé sur un système Red Hat Enterprise Linux ou CentOS Linux.
* Vous devez disposer des informations d'identification utilisateur root pour le système Linux sur lequel Unified Manager est installé.




== Étapes

. Connectez-vous en tant qu'utilisateur root au système Linux sur lequel Unified Manager s'exécute.
. Modifier le mot de passe umadmin : `passwd umadmin`
+
Le système vous invite à entrer un nouveau mot de passe pour l'utilisateur umadmin.





== Une fois que vous avez terminé

Si Unified Manager est installé dans un environnement Veritas Cluster Server (VCS), vous devez modifier le mot de passe umadmin sur le second nœud de la configuration VCS. Le mot de passe umadmin pour les deux nœuds doit être le même.
