---
permalink: health-checker/task-creating-a-jdbc-data-source-using-birt.html 
sidebar: sidebar 
keywords: Unified Manager 
summary: 'Après avoir créé le nouveau rapport à l"aide de BIRT, vous devez créer une source de données pour connecter le rapport à Unified Manager.' 
---
= Création d'une source de données JDBC à l'aide de BIRT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir créé le nouveau rapport à l'aide de BIRT, vous devez créer une source de données pour connecter le rapport à Unified Manager.



== Avant de commencer

Vous devez avoir créé un rapport à l'aide de BIRT.

Vous devez avoir téléchargé et installé MySQL Connector/J.

Vous devez avoir créé un utilisateur de base de données avec le rôle Report Schema.



== Étapes

. Dans Eclipse, sélectionnez *Data Explorer* > *Data sources* > *New Data Source*.
. Sélectionnez *Créer à partir d'un type de source de données dans la liste* suivante.
. Sélectionnez *Source de données JDBC*, puis cliquez sur *Suivant*.
. Dans la boîte de dialogue *Nouveau profil de source de données JDBC*, sélectionnez *com.mysql.jdbc.Driver(v5.1)*.
+
.. Si le pilote MySQL ne s'affiche pas, cliquez sur *gérer les pilotes*.
.. Dans la boîte de dialogue *gérer les pilotes JDBC*, cliquez sur *Ajouter*.
.. Naviguez jusqu'à l'emplacement où le connecteur MySQL/J `.jar` le fichier a été installé, puis sélectionnez le fichier.
.. Cliquez sur *OK*.
+
Vous devriez pouvoir afficher et sélectionner le pilote MySQL.



. Entrez le nom d'hôte complet ou l'adresse IP de l'instance Unified Manager au format approprié :
+
|===
| Type d'adresse | Format 


 a| 
IPv4
 a| 
`jdbc:mysql://xx.xx.xx.xx:3306/ocum_report`



 a| 
IPv6
 a| 
`jdbc:mysql://address=(protocol=tcp)(host=xx:xx:xx:xx:xx:xx:xx:xx)(port=3306)/ocum_report`

|===
. Entrez le nom d'utilisateur de l'utilisateur de la base de données, entrez le mot de passe, puis cliquez sur *Terminer*.

