---
permalink: health-checker/task-changing-the-maintenance-user-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez modifier le mot de passe utilisateur responsable de la maintenance d"Unified Manager si nécessaire.' 
---
= Modification du mot de passe utilisateur de maintenance sous Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le mot de passe utilisateur responsable de la maintenance d'Unified Manager si nécessaire.



== Étapes

. Dans la page de connexion à l'interface utilisateur Web de Unified Manager, cliquez sur *Mot de passe oublié*.
+
Une page s'affiche et vous demande le nom de l'utilisateur dont vous souhaitez réinitialiser le mot de passe.

. Entrez le nom d'utilisateur et cliquez sur *Envoyer*.
+
Un e-mail contenant un lien pour réinitialiser le mot de passe est envoyé à l'adresse e-mail définie pour ce nom d'utilisateur.

. Cliquez sur le lien *reset mot de passe* dans l'e-mail et définissez le nouveau mot de passe.
. Revenez à l'interface utilisateur Web et connectez-vous à Unified Manager à l'aide du nouveau mot de passe.




== Une fois que vous avez terminé

Si Unified Manager est installé dans un environnement MSCS (Microsoft Cluster Server), vous devez modifier le mot de passe utilisateur de maintenance sur le second nœud de la configuration MSCS. Le mot de passe utilisateur de maintenance pour les deux nœuds doit être identique.
