---
permalink: config/task-changing-the-local-user-password.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez modifier votre mot de passe de connexion utilisateur local afin d"éviter tout risque de sécurité.' 
---
= Modification du mot de passe de l'utilisateur local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier votre mot de passe de connexion utilisateur local afin d'éviter tout risque de sécurité.



== Avant de commencer

Vous devez être connecté en tant qu'utilisateur local.



== Description de la tâche

Les mots de passe de l'utilisateur de maintenance et des utilisateurs distants ne peuvent pas être modifiés à l'aide de ces étapes. Pour modifier le mot de passe d'un utilisateur distant, contactez l'administrateur de votre mot de passe. Pour modifier le mot de passe utilisateur de maintenance, reportez-vous à la section link:../health-checker/task-using-the-maintenance-console.html["Utilisation de la console de maintenance"].



== Étapes

. Connectez-vous à Unified Manager.
. Dans la barre de menus supérieure, cliquez sur l'icône utilisateur, puis sur *changer mot de passe*.
+
L'option *Modifier le mot de passe* n'est pas affichée si vous êtes un utilisateur distant.

. Dans la boîte de dialogue *Modifier le mot de passe*, entrez le mot de passe actuel et le nouveau mot de passe.
. Cliquez sur *Enregistrer*.




== Une fois que vous avez terminé

Si Unified Manager est configuré dans une configuration haute disponibilité, vous devez modifier le mot de passe sur le second nœud du setup. Les deux instances doivent avoir le même mot de passe.
