---
permalink: install/concept-requirements-and-limitations-for-unified-manager-in-mscs.html 
sidebar: sidebar 
keywords:  
summary: 'Avant d"installer Unified Manager dans un environnement de mise en cluster de basculement, assurez-vous que les nœuds de cluster sont correctement configurés pour prendre en charge Unified Manager.' 
---
= Configuration requise pour Unified Manager dans un environnement de mise en cluster de basculement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer Unified Manager dans un environnement de mise en cluster de basculement, assurez-vous que les nœuds de cluster sont correctement configurés pour prendre en charge Unified Manager.

Vous devez vous assurer que la configuration du cluster de basculement répond aux exigences suivantes :

* Les deux nœuds de cluster doivent exécuter la même version de Microsoft Windows Server.
* La même version de Unified Manager doit être installée à l'aide du même chemin sur les deux nœuds du cluster.
* La mise en cluster de basculement doit être installée et activée sur les deux nœuds.
+
Consultez la documentation Microsoft pour obtenir des instructions.

* Vous devez avoir utilisé une structure avec commutateur Fibre Channel ou un stockage iSCSI pour créer un disque de données partagé en tant que stockage interne
* Facultatif : avec SnapDrive pour Windows, vous devez créer un emplacement partagé accessible aux deux nœuds du programme de configuration haute disponibilité.
+
Pour plus d'informations sur l'installation et la création d'un emplacement partagé, reportez-vous au _SnapDrive pour le Guide d'installation de Windows.

+
Vous pouvez également gérer les LUN via l'interface de ligne de commandes du système de stockage. Consultez la matrice de compatibilité SnapDrive pour Windows pour plus d'informations.

* Le Perl doit être installé avec `XML::LibXML` et `File::chdir` modules pour que les scripts fonctionnent.
* Il ne doit y avoir que deux nœuds au sein de la configuration du cluster.
* Le type de quorum « nœud et disque majoritaire » doit être utilisé pour la mise en cluster de basculement.
* Vous devez avoir configuré une adresse IP partagée avec un FQDN correspondant à utiliser comme adresse IP globale du cluster pour accéder à Unified Manager.
* Le mot de passe de l'utilisateur responsable de la maintenance de Unified Manager sur les deux nœuds doit être identique.
* Vous devez avoir utilisé uniquement une adresse IP IPv4.

