---
permalink: install/reference-completing-the-worksheet-um.html 
sidebar: sidebar 
keywords:  
summary: 'Avant d"installer et de configurer Unified Manager, vous devez disposer facilement d"informations spécifiques sur votre environnement. Vous pouvez enregistrer les informations dans la fiche.' 
---
= Remplir la fiche
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer et de configurer Unified Manager, vous devez disposer facilement d'informations spécifiques sur votre environnement. Vous pouvez enregistrer les informations dans la fiche.



== Informations sur l'installation de Unified Manager

Détails requis pour installer Unified Manager.

|===
| Système sur lequel le logiciel est déployé | Votre valeur 


 a| 
Adresse IP du serveur ESXi (VMware uniquement)
 a| 



 a| 
Nom de domaine complet de l'hôte
 a| 



 a| 
Adresse IP de l'hôte
 a| 



 a| 
Masque de réseau
 a| 



 a| 
Adresse IP de la passerelle
 a| 



 a| 
Adresse DNS principale
 a| 



 a| 
Adresse DNS secondaire
 a| 



 a| 
Domaines de recherche
 a| 



 a| 
Nom d'utilisateur de maintenance
 a| 



 a| 
Mot de passe utilisateur de maintenance
 a| 

|===


== Informations sur la configuration de Unified Manager

Détails de la configuration d'Unified Manager après l'installation. Certaines valeurs sont facultatives en fonction de votre configuration.

|===
| Réglage | Votre valeur 


 a| 
Adresse e-mail de l'utilisateur de maintenance
 a| 



 a| 
Serveur NTP (VMware uniquement)
 a| 



 a| 
Nom d'hôte ou adresse IP du serveur SMTP
 a| 



 a| 
Nom d'utilisateur SMTP
 a| 



 a| 
Mot de passe SMTP
 a| 



 a| 
Port SMTP
 a| 
25 (valeur par défaut)



 a| 
E-mail à partir duquel les notifications d'alerte sont envoyées
 a| 



 a| 
Nom d'hôte ou adresse IP du serveur d'authentification
 a| 



 a| 
Nom d'administrateur Active Directory ou nom distinctif de liaison LDAP
 a| 



 a| 
Mot de passe Active Directory ou mot de passe de liaison LDAP
 a| 



 a| 
Nom distinctif de la base du serveur d'authentification
 a| 



 a| 
URL du fournisseur d'identités
 a| 



 a| 
Métadonnées du fournisseur d'identités
 a| 



 a| 
Adresse IP de l'hôte de destination de l'interruption SNMP
 a| 



 a| 
Port SNMP
 a| 

|===


== Informations sur le cluster

Détails des systèmes de stockage que vous allez gérer à l'aide de Unified Manager.

|===
| Cluster 1 de N | Votre valeur 


 a| 
Nom d'hôte ou adresse IP de gestion du cluster
 a| 



 a| 
Nom d'utilisateur de l'administrateur ONTAP

[NOTE]
====
L'administrateur doit avoir reçu le rôle « admin ».

==== a| 



 a| 
Mot de passe administrateur ONTAP
 a| 



 a| 
Protocole (HTTP ou HTTPS)
 a| 

|===