---
permalink: install/task-upgrading-mysql-on-linux.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez effectuer une mise à niveau vers une version plus récente de MySQL sur le serveur Linux sur lequel Unified Manager est installé afin d"obtenir des correctifs pour les vulnérabilités de sécurité.' 
---
= Mise à niveau de MySQL sur Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une mise à niveau vers une version plus récente de MySQL sur le serveur Linux sur lequel Unified Manager est installé afin d'obtenir des correctifs pour les vulnérabilités de sécurité.



== Avant de commencer

Vous devez disposer de privilèges root pour le système Linux sur lequel Unified Manager est installé.



== Description de la tâche

Vous pouvez uniquement mettre à niveau vers des mises à jour mineures de MySQL 5.7, par exemple 5.7.1 à 5.7.2 . Vous ne pouvez pas effectuer la mise à niveau vers les versions principales de MySQL, par exemple la version 5.8.



== Étapes

. Connectez-vous en tant qu'utilisateur root sur la machine hôte Unified Manager.
. Téléchargez le dernier serveur de communauté MySQL `.rpm` offre groupée sur le système cible.
. Décompressez le bundle dans un répertoire du système cible.
. Vous en aurez plusieurs `.rpm` Les packages du répertoire après avoir détarbré le bundle, mais Unified Manager n'a besoin que des packages RPM suivants :
+
** mysql-community-client-5.7.x
** mysql-community-libs-5.7.x
** mysql-community-server-5.7.x
** mysql-community-common-5.7.x
** mysql-community-libs-compat-5.7.x Supprimer tous les autres `.rpm` packs : L'installation de tous les paquets dans un ensemble RPM ne causera aucun problème.


. Arrêtez le service Unified Manager et le logiciel MySQL associé dans l'ordre indiqué :
. Appelez la mise à niveau de MySQL à l'aide de la commande suivante : `yum install *.rpm`
+
`*.rpm` se réfère au `.rpm` Paquets dans le répertoire où vous avez téléchargé la nouvelle version de MySQL.

. Démarrer Unified Manager dans l'ordre indiqué :

