---
permalink: install/task-changing-the-jboss-password.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez créer un nouveau mot de passe JBoss personnalisé pour remplacer le mot de passe par défaut défini lors de l"installation. Cette tâche est facultative, mais certains sites peuvent nécessiter cette fonctionnalité de sécurité pour remplacer le paramètre par défaut d"installation d"Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.' 
---
= Modification du mot de passe JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un nouveau mot de passe JBoss personnalisé pour remplacer le mot de passe par défaut défini lors de l'installation. Cette tâche est facultative, mais certains sites peuvent nécessiter cette fonctionnalité de sécurité pour remplacer le paramètre par défaut d'installation d'Unified Manager. Cette opération modifie également le mot de passe que JBoss utilise pour accéder à MySQL.



== Avant de commencer

* Vous devez avoir un accès utilisateur root au système Red Hat Enterprise Linux ou CentOS sur lequel Unified Manager est installé.
* Pour accéder à ces informations, vous devez pouvoir `password.sh` script dans le répertoire `/opt/netapp/essentials/bin`.




== Étapes

. Connectez-vous en tant qu'utilisateur root sur le système.
. Arrêter les services Unified Manager en entrant les commandes suivantes dans l'ordre indiqué : `service ocieau stop``service ocie stop`
+
N'arrêtez pas le logiciel MySQL associé.

. Entrez la commande suivante pour lancer le processus de modification du mot de passe : `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. Lorsque vous y êtes invité, saisissez l'ancien mot de passe JBoss.
+
Le mot de passe par défaut est `D11h1aMu@79%`.

. Lorsque vous y êtes invité, saisissez le nouveau mot de passe JBoss, puis saisissez-le une deuxième fois pour confirmation.
. Une fois le script terminé, démarrez les services Unified Manager en entrant les commandes suivantes dans l'ordre indiqué : `service ocie start``service ocieau start`
. Une fois tous les services démarrés, vous pouvez vous connecter à l'interface utilisateur de Unified Manager.

