---
permalink: install/task-uninstalling-unified-manager-win.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez désinstaller Unified Manager de Windows à l"aide de l"Assistant programmes et fonctionnalités ou en effectuant une désinstallation automatique à partir de l"interface de ligne de commande.' 
---
= Désinstallation de Unified Manager sous Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Vous pouvez désinstaller Unified Manager de Windows à l'aide de l'Assistant programmes et fonctionnalités ou en effectuant une désinstallation automatique à partir de l'interface de ligne de commande.



== Avant de commencer

* Vous devez disposer des privilèges d'administrateur Windows.
* Tous les clusters (sources de données) doivent être supprimés du serveur Unified Manager avant de désinstaller le logiciel.
* Le serveur Unified Manager ne doit pas être connecté de façon active à un fournisseur de données externe comme Graphite.
+
Si c'est le cas, vous devez supprimer la connexion à l'aide de la console de maintenance Unified Manager.





== Étapes

. Lorsqu'il est installé dans une configuration haute disponibilité, supprimez les ressources du groupe de services haute disponibilité, puis supprimez le groupe de services haute disponibilité avant de désinstaller Unified Manager des deux nœuds.
. Désinstallez Unified Manager en choisissant l'une des options suivantes :
+
|===
| Pour désinstaller Unified Manager à partir de... | Alors... 


 a| 
Assistant programmes et fonctionnalités
 a| 
.. Accédez à *panneau de configuration* > *Programme et fonctionnalités*.
.. Sélectionnez OnCommand Unified Manager, puis cliquez sur *Désinstaller*.




 a| 
Ligne de commande
 a| 
.. Connectez-vous à la ligne de commande Windows à l'aide des privilèges d'administrateur.
.. Accédez au répertoire OnCommand Unified Manager et exécutez la commande suivante : `+msiexec /x {A78760DB-7EC0-4305-97DB-E4A89CDFF4E1} /qn /l*v %systemdrive%\UmUnInstall.log+`


|===
+
Si le contrôle de compte d'utilisateur (UAC) est activé sur le serveur et que vous êtes connecté en tant qu'utilisateur de domaine, vous devez utiliser la méthode de désinstallation de ligne de commande.

+
Unified Manager est désinstallé de votre système.

. Désinstallez les packages tiers et données suivants qui ne sont pas supprimés pendant la désinstallation de Unified Manager :
+
** Packages tiers : JRE, MySQL, Microsoft Visual C&#43;&#43; 2015 Redistributable et 7zip
** Données d'application MySQL générées par Unified Manager
** Les journaux d'application et le contenu du répertoire des données d'application



